### ISSUE TITLE
How to get geos 3.12.1 installed?

### ISSUE THREAD

**Issue by theroggy** [conda-forge/geos-feedstock#72]
I'm trying to install geos 3.12.1, but as far as I understand it seems that it is still pinned to 3.12.0 in the packages I use that depend on geos.

If I run `mamba repoquery whoneeds geos` I get the following:

```
 Name          Version Build           Depends                   Channel
-----------------------------------------------------------------------------
 libgdal       3.8.0   h41773de_4      geos >=3.12.0,<3.12.1.0a0 conda-forge
 librttopo     1.1.0   h92c5fdb_14     geos >=3.12.0,<3.12.1.0a0 conda-forge
 libspatialite 5.1.0   hbf340bc_1      geos >=3.12.0,<3.12.1.0a0 conda-forge
 shapely       2.0.2   py310h839b4a8_0 geos >=3.12.0,<3.12.1.0a0 conda-forge
```

I had a look at the shapely feedstock, but even though geos 3.12.1 has been released 2 weeks I don't see a pull request created by `regro-cf-autotick-bot` to rebuild it using geos 3.12.1 like usual when new geos version are released.

Does there needs to be an action from your side still to get this process started or ?

**Comment by xylar** [comment]
A migrator just started:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5146

You should be able to install geos 3.12.1 once that has progressed through the packages you are using.
https://conda-forge.org/status/#geos3121

**Comment by theroggy** [comment]
Thanks!
