### ISSUE TITLE
Windows builds lack .pc (pkg-config) file

### ISSUE THREAD

**Issue by mfansler** [conda-forge/geos-feedstock#74]
Other platforms ship with a pkg-config file (geos.pc), but not the Windows builds. This lack of symmetry propagates as platform-specific build code. It would be great if this could be resolved!

I.e., please ship with `%PREFIX%\Library\lib\pkgconfig\geos.pc`.

Example downstream issue: https://github.com/conda-forge/r-terra-feedstock/pull/96

**Comment by gillins** [comment]
Currently only happens on non-MSVC targets (see https://github.com/libgeos/geos/blob/main/tools/CMakeLists.txt#L82). Happy to receive a PR with a patch, but maybe raise this upstream?

**Comment by gillins** [comment]
Always slightly nervous linking MSVC code with gcc code BTW, never quite sure what will happen.

**Comment by mfansler** [comment]
@gillins thanks for identifying the source! I sent a PR to remove the condition.

> Always slightly nervous linking MSVC code with gcc code BTW, never quite sure what will happen.

I'll turn on the unit testing to check the builds on the downstream package are actually functional.

**Comment by gillins** [comment]
> I'll turn on the unit testing to check the builds on the downstream package are actually functional.

Thanks @mfansler, really interested to hear how this goes. I've always thought we may need to have a `g++` variant of the builds for Windows to properly support R but this is A Lot Of Work....

**Comment by mfansler** [comment]
Just to follow-up: indeed no success in mixing the MSVC-compiled lib with GCC compilation. There are a couple relevant PRs (`r-terra` [PR96](https://github.com/conda-forge/r-terra-feedstock/pull/96), [PR97](https://github.com/conda-forge/r-terra-feedstock/pull/97)) to see how this went - or didn't. The second one attempted switching out to clang, but the `terra` package itself is using C++23 features not yet available in clang/MSVC.

The pkg-config was also ultimately not so useful because the .pc for PROJ needed an openssl .pc, which similarly isn't packaged and I wasn't motivated to accept that indefinite PR quest.
