### ISSUE TITLE
Update GEOS to 3.5.1 when it is released

### ISSUE THREAD

**Issue by gillins** [conda-forge/geos-feedstock#9]
Judging by progress in trunk, it will have Python3.5 on Windows (VC 2015) support. This will mean we can remove the ugly patches that are marked [win and py35].

**Comment by ocefpaf** [comment]
@pelson is `cartopy` OK with `geos 3.5.1`? If not we must pin it there before updating `geos` here to avoid breaking envs.

**Comment by pelson** [comment]
> @pelson is cartopy OK with geos 3.5.1?

Who knows! :smile: 
Once we have a distribution, we can run the cartopy tests against it and see. I appreciate the ping, but I don't think we should hold up downstream things for fear of breaking upstream things - we can fix as we go, and pin the cartopy recipe as appropriate.

:+1:

**Comment by ocefpaf** [comment]
We have `3.5.1` now I will experiment with `cartopy` locally and if things are OK change the pinning.

**Comment by ocefpaf** [comment]
Closing this as we have
- https://github.com/conda-forge/shapely-feedstock/pull/13
- https://github.com/conda-forge/cartopy-feedstock/pull/21
- https://github.com/conda-forge/conda-forge.github.io/pull/268

in place.
